### ISSUE TITLE
Attempts to level bed in mid-air

### ISSUE THREAD

**Issue by ccarlson71** [TechnoSwiss/MPMD-AutoBedLevel-Cal#5]
After what appears to be a G28, the head lowers about halfway down towards the bed, then appears to do a single four-point leveling which (understandably) doesn't actually trigger the bed switches. It then  stops the 'calibration' process and outputs values as though it had completed successfully.

I'm not sure where to even begin looking to troubleshoot this behavior.

**Comment by TechnoSwiss** [comment]
The script was originally written for the 8 micro-step boards, and it hadn't occurred to me that it needed to be updated for the 16 micro-step boards, but I'm going to bet that's the issue you've run into. I'll get the script updated so it can switch between the 2, but in the meantime if you wanted to test the fix out, look for the section that says "step_mm = 57.14" and change it to "step_mm = 114.28" and that should fix it.

**Comment by ccarlson71** [comment]
Will try it ASAP. Thanks, @TechnoSwiss !

**Comment by ccarlson71** [comment]
...and that did the trick. I didn't realize I had the new 16-step boards.

Thanks a ton, both for the script and the quick help.
